### PR TITLE
Add feature for date error handling

### PR DESCRIPTION
**Pull request by yannikbuhl**
This enhancement provides a method for error handling when the date parameters `from` and `to` of `get_everything` are not provided in correct ISO format. The new `tryCatch` function allows for different date formats and helps users to make sure the HTTP request comes with a correct date format.

### CODE REVIEW

**Comment by friep** [comment]
nice work, @yannikbuhl - nicely done and :100:  for putting the accepted formats in a separate vector: makes it much more readable :tada:  
I'm not sure I am a fan of continuing with a warning if the user specifies the date in the wrong format. i'd just stop and give back the error.
as a user, I tend to ignore "the red text" if my code succeeded. Maybe it's just me but i'd be happily analyzing my data and then wondering "mhh why didn't my date range not apply?". 
Does that make sense? :)

**Comment by yannikbuhl** [comment]
Thanks for the feedback :-) You're totally right, I was actually already wondering why `tryCatch` does not stop but rather only warns, I thought that was kind of build-in, but as it is, it's definitely confusing! But I'll fix it! :) And thx for the fix of the build!

**Comment by yannikbuhl** [comment]
Fixed error handle for date formats: Update lets the function stop with a meaningful error message when various accepted Date Formats are not met.

**Comment by friep** [comment]
thanks for the update! Looks good! :tada: 

What we need to do still:
- write tests that make the code fail (e.g. pass in format that is not supported)
- maybe also write test that cover the supported formats to be sure that they are accepted by NewsAPI (maybe we shouldn't use get_everything for this but just make the request using build_newsanchor_url and make_newsanchor_get_request). 
- fix the build :wink:

**Comment by yannikbuhl** [comment]
Fixed the **build**, wrote **tests** that make the code fail (e.g. pass in format that is not supported).

What's missing: *** test that cover the supported formats** 👍

**Comment by friep** [comment]
nice! :+1: 
 overwriting the `to`  and `from` with the parsed date in try is a very good idea. If it succeeds, we'll always pass `%Y-%m-%d` to NewsAPI and that should always be supported by NewsAPI. 

I realized that after I had already written some code during writing i stumbled upon a curious thing with the as.Date function. 

``` r
valid_date_formats <- c("%Y-%m-%d", 
                        "%Y/%m/%d",
                        "%Y.%m.%d",
                        "%Y %m %d",
                        "%Y,%m,%d",
                        "%Y-%m-%d %H:%M:%S",
                        "%Y/%m/%d %H:%M:%S",
                        "%Y.%m.%d %H:%M:%S",
                        "%Y %m %d %H:%M:%S",
                        "%Y,%m,%d %H:%M:%S")
now_time <- as.POSIXct(Sys.time())
# go through all formats, convert timestamp to it and try to parse it back to Date
for(d in valid_date_formats){
  print("---")
  print(d)
  # format posix to string of format d
  s <- format(now_time, d)
  print(s)
  # parse again.
  print(as.Date(s, tryFormats=valid_date_formats))
}
#> [1] "---"
#> [1] "%Y-%m-%d"
#> [1] "2019-02-13"
#> [1] "2019-02-13"
#> [1] "---"
#> [1] "%Y/%m/%d"
#> [1] "2019/02/13"
#> [1] "2019-02-13"
#> [1] "---"
#> [1] "%Y.%m.%d"
#> [1] "2019.02.13"
#> Error in charToDate(x): character string is not in a standard unambiguous format
```

Created on 2019-02-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

MWE:
``` r
as.Date("2019.02.12", tryFormats=c("%Y.%m.%d"))
#> Error in charToDate(x): character string is not in a standard unambiguous format
as.Date("2019.02.12", "%Y.%m.%d")
#> [1] "2019-02-12"
```

Created on 2019-02-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

@yannikbuhl  can you test that this occurs on windows as well? am i missing something obvious? 
If it takes too much time to fix this, I'd suggest we reduce the  number of supported formats to two or three standard ones (%Y-%m-%d, %Y-%m-%d %H:%M:%S for example).

**Comment by friep** [comment]
seems like `tryFormats` was only introduced in R 3.5.0 (released April 2018). 
i guess on older R versions, `tryFormats` is simply ignored (and hence I got the standard `not in a standard unambiguous format` error that you get when you feed anything else than `Y-m-d` or `Y/m/d` to as.Date().

I propose to just leave it to the user to format their date correctly to one of the unambiguous formats and we just use `as.Date()` without specifying format.

**Comment by friep** [comment]
only YYYY-mm-dd is allowed now. 
I think it's better to not rely on such a new version of R. 
just using `as.Date()` without specifying the format is also not super safe:
`as.Date("01/01/2000")` -> `0001-01-20` -> wtf??
(see [here](https://stackoverflow.com/questions/14755425/what-are-the-standard-unambiguous-date-formats)

**Pull request merged**
