### PR TITLE
Resolving Issue #44

### PR DESCRIPTION
**Pull request by MDshuey**
I allow the qInTitle parameter to be used. If parameter-checking needs to be introduced pls let me know.

### CODE REVIEW

**Comment by yannikbuhl** [comment]
Thank you so much @MDshuey for your PR. We'll look into it soon and hopefully merge it thereafter. All the best!

**Comment by friep** [comment]
@MDshuey could you add me as an external contributor to your fork? then i could push some commits to this PR and we could merge it :)

**Comment by MDshuey** [comment]
@friep thanks for your help! I'm still figuring out package dev so this will help me contribute more in the future

**Comment by friep** [comment]
@MDshuey sorry, could you resend the invitation? I was on holiday and it is now expired (more than 7 days passed :( )

**Comment by MDshuey** [comment]
Just resent the invitation, thanks!

**Comment by friep** [comment]
thanks @MDshuey for your contribution. i'll add an item in NEWS.md after merging this PR mentioning you!

**Pull request merged**
